[package]
name = "nk_rust"
version = "0.0.0"
edition = "2021"
authors = [
    "Michael Polinski <michaelp@u.northwestern.edu>",
    "Hanming Wang <hanmingwang2022@u.northwestern.edu>",
    "Qingwei Lan <qingweilan2022@u.northwestern.edu>",
    "Peter Dinda <pdinda@northwestern.edu>",
]

[lib]
crate-type = ["staticlib"]

[build-dependencies]
bindgen = "0.59.2"

[dependencies]
bitfield = "0.13.2"
x86_64 = "0.14.9"
lock_api = "0.4.7"
